PIX_SCALE = 0.1
TILE_DIM = 19200
TRACT_RADIUS = 0.2667  # 0.4  # deg: 2 * (TILE_DIM / 2)**2 * PIX_SCALE / 3600.0
PATCH_SIZE = 21600  # 1x1 patches  # 4800  # 4x4 patches
EUCLID_SKYMAP_NAME = "Euclid_Q1"
EUCLID_SKYMAP_FILENAME = "EuclidQ1SkyMap_autogen.py"
EUCLID_COLLECTION_NAME = "Euclid/Q1"  # No trailing slash

EUCLID_BGMOD_DATASET_TYPE_NAME = "euclidBgMod"
EUCLID_BGMOD_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/bgmod"

EUCLID_COADD_DATASET_TYPE_NAME = "euclidCoadd"
EUCLID_COADD_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/coadd"

EUCLID_FLAGMAP_DATASET_TYPE_NAME = "euclidFlagMap"
EUCLID_FLAGMAP_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/flagmap"

EUCLID_GRIDPSF_DATASET_TYPE_NAME = "euclidGridPsf"
EUCLID_GRIDPSF_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/gridpsf"

EUCLID_CATALOGPSF_DATASET_TYPE_NAME = "euclidCatalogPsf"
EUCLID_CATALOGPSF_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/catalogpsf"

EUCLID_RMSMAP_DATASET_TYPE_NAME = "euclidRmsMap"
EUCLID_RMSMAP_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/rmsmap"

EUCLID_SEGMAP_DATASET_TYPE_NAME = "euclidSegMap"
EUCLID_SEGMAP_COLLECTION_NAME = f"{EUCLID_COLLECTION_NAME}/segmap"
